services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123#
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
